steps:
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - 'run'
    - '--image=gcr.io/${_PROJECT}/${_DEPLOYNAME}:${_VERSION}'
    - '--location=${_ZONE}'
    - '--cluster=${_GKE_CLUSTER}'

substitutions:
  _PROJECT: tough-bearing-259612
  _ZONE: europe-west1-b
  _GKE_CLUSTER: standard-cluster-1

  _CONTAINERNAME: bdeploy
  _DEPLOYNAME: bdeploy	

  _VERSION: '1.3'